openapi: 3.0.0
info:
  title: Tech Challenge API
  description: This is a Tech Challenge API interface design / specification
  license:
    name: Tech Challenge API
  version: 0.0.1
servers:
- url: https://localhost:8080/
paths:
  /records:
    get:
      tags:
      - get records
      summary: Gets all the records
      operationId: get_record
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecordStatus'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "405":
          description: Method Not Allowed
        "415":
          description: Unsupported Media Type / Unspecified Content Type
        "500":
          description: Internal Server Error
        "504":
          description: Gateway timeout
      x-openapi-router-controller: swagger_server.controllers.get_records_controller
  /records/create:
    post:
      tags:
      - create records
      summary: Creates a new record.
      operationId: create_record
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Record'
        required: true
      responses:
        "201":
          description: Created
        "415":
          description: Unsupported Media Type / Unspecified Content Type
        "500":
          description: Internal Server Error
        "504":
          description: Gateway timeout
      x-openapi-router-controller: swagger_server.controllers.create_records_controller
  /records/{recordId}:
    get:
      tags:
      - get a single record
      summary: Returns a record by ID.
      operationId: get_recordby_id
      parameters:
      - name: recordId
        in: path
        description: The ID of the record to return.
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
      responses:
        "200":
          description: A record object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: The specified record ID is invalid (not a number).
        "404":
          description: A user with the specified ID was not found.
        default:
          description: Unexpected error
      x-openapi-router-controller: swagger_server.controllers.get_a_single_record_controller
components:
  schemas:
    RecordStatus:
      type: array
      items:
        $ref: '#/components/schemas/StatusModel'
    Record:
      type: array
      items:
        $ref: '#/components/schemas/RecordModel'
    StatusModel:
      type: object
      properties:
        status:
          type: string
          example: "yes"
      example:
        status: "yes"
    RecordModel:
      type: object
      properties:
        status:
          type: string
          example: "yes"
    inline_response_200:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 4
        name:
          type: string
          example: Jessica Smith
      example:
        name: Jessica Smith
        id: 4

